### ISSUE TITLE
symfony 2.8 or 3

### ISSUE THREAD

**Issue by xorgxx** [tomazahlin/symfony-mailer-bundle#1]
Hi, i wanted to try your system mail but it cant be install on symfony 2.8! do you plan to update for ?

**Comment by tomazahlin** [comment]
I can take a look over the weekend, to make it installable for 2.8.

**Comment by xorgxx** [comment]
thank waiting ...

**Comment by tomazahlin** [comment]
I have updated composer.json. Tag 2.1.1 is now installable with Symfony 2.8 as well.

If your composer still has old version cached, use "composer clear-cache". Then "composer require tomazahlin/symfony-mailer-bundle" should work.

**Comment by xorgxx** [comment]
Hi i m try ing to update same projet how use your great bundle.
i simce that i can update symfony 3.1.2.

can you try to help?
thank

**Comment by xorgxx** [comment]
Hi i m try ing to update same projet how use your great bundle.
i simce that i can update symfony 3.1.2.

```
Using version ^2.2 for tomazahlin/symfony-mailer-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for tomazahlin/symfony-mailer-bundle ^2.2 -> satisfiable by tomazahlin/symfony-mailer-bundle[2.2].
    - Conclusion: remove symfony/symfony v3.1.2
    - Conclusion: don't install symfony/symfony v3.1.2
```

can you try to help?
thank

**Comment by tomazahlin** [comment]
Yes, try to use "dev-master" for my bundle, in your composer.json. I did not try it yet myself, but user on the top said he tested it. Once I can verify it myself, I can then create new tagged release.

**Comment by xorgxx** [comment]
well i just install ! thank - i will see no probleme ....
