### ISSUE TITLE
form to send email

### ISSUE THREAD

**Issue by xorgxx** [tomazahlin/symfony-mailer-bundle#2]
Hi i'm waiting for the ne version (Sf 8).

for raison i want to see if it's possible to add systeme of form by use to send email, and maybe put in database to have security.
for now i have this form but i dont want to have 2 bundle for the same think Sending email.

is that possible? i gues yes.

Sorry for my bad english.

**Comment by tomazahlin** [comment]
Please explain, sorry I did not understand what you need.

**Comment by xorgxx** [comment]
hi i see too think, to add form for user field in he new contact email and send. Because hosting system are not very save : to add possibility to archive all mail send in the database?

thank for all

**Comment by tomazahlin** [comment]
Of course it is possible, that is totally up to you, what you will do. This bundle doesn't do any persisting to the database on it's own, but you can do that by yourself.
